# 此文件为ecat集成的配置文件，无此文件则下面均为无。
dependencies: # 依赖的其他ecat集成的信息。可选项，默认无
  - artifactId: integration-ecat-common

web-platform: # 需要支持的web平台的能力。可选项，默认无
  ui: false # 是否支持web平台显示功能，必填项
  api: false # 是否支持web平台api功能，必填项
